/**
 * Offline English→Chinese word meta (POS + meaning) from ECDICT.
 *
 * Dataset: https://github.com/skywind3000/ECDICT (MIT)
 * Regenerated by: `pnpm dict:build` → scripts/build-ecdict-meta.py
 */

import {
  entryToLine,
  parseWordLine,
  parseWords,
  speakTextFromEntry,
} from "./dictation";
import ecdictMeta from "./ecdict-meta.json";

export interface WordMeta {
  pos?: string;
  meaning?: string;
}

/** Compact map: lowercased word → `"pos|meaning"` (pos may be empty). */
const META = ecdictMeta as Record<string, string>;

const POS_PREFIX_RE =
  /^(n\.|v\.|vt\.|vi\.|adj\.|adv\.|prep\.|conj\.|pron\.|num\.|art\.|int\.|aux\.|abbr\.|contr\.|a\.)\s*/i;

/**
 * 仅做清理，保留完整释义（含多义项）。多义项以「；」分隔，由构建脚本保证。
 */
function normalizeMeaning(raw: string): string {
  return raw.trim();
}

/**
 * 取释义的首个义项（按「；」/`;` 切分），用于默认折叠展示。
 * 无分号时原样返回。
 */
export function firstSense(meaning: string): string {
  const idx = meaning.search(/[；;]/);
  return idx === -1 ? meaning.trim() : meaning.slice(0, idx).trim();
}

/**
 * 将多义项释义按「；」/`;` 拆成每个义项的数组。单义项返回长度为 1 的数组。
 */
export function splitSenses(meaning: string): string[] {
  return meaning
    .split(/[；;]/)
    .map((s) => s.trim())
    .filter(Boolean);
}

/**
 * Split a gloss like `"n. 苹果"` into `{ pos, meaning }`.
 */
function splitPosMeaning(raw: string): WordMeta | null {
  let text = raw.trim();
  if (!text) return null;
  if (text.startsWith("【")) return null;

  let pos: string | undefined;
  const posMatch = text.match(POS_PREFIX_RE);
  if (posMatch) {
    pos = posMatch[1]!.toLowerCase();
    if (pos === "a.") pos = "adj.";
    text = text.slice(posMatch[0].length).trim();
  }

  text = normalizeMeaning(text);
  if (!pos && !text) return null;
  return { pos, meaning: text || undefined };
}

function decodeStored(raw: string): WordMeta | null {
  // Stored as "pos|meaning" (pos may be empty → "|meaning")
  const bar = raw.indexOf("|");
  if (bar === -1) return splitPosMeaning(raw);

  const pos = raw.slice(0, bar).trim() || undefined;
  const meaning = normalizeMeaning(raw.slice(bar + 1));
  if (!pos && !meaning) return null;
  return { pos, meaning: meaning || undefined };
}

/**
 * Look up a single word/phrase in the offline ECDICT subset.
 * Matching is case-insensitive; returns null when absent.
 */
export function lookupWordMeta(word: string): WordMeta | null {
  const key = word.trim().toLowerCase();
  if (!key) return null;

  const direct = META[key];
  if (direct) return decodeStored(direct);

  // Strip trailing punctuation / soft hyphens that OCR sometimes leaves
  const stripped = key.replace(/[^a-z0-9\s'\-./]/gi, "").trim();
  if (stripped && stripped !== key) {
    const again = META[stripped];
    if (again) return decodeStored(again);
  }

  // "a/an" style alternatives — try each side
  if (key.includes("/")) {
    for (const part of key.split("/")) {
      const meta = lookupWordMeta(part);
      if (meta) return meta;
    }
  }

  return null;
}

/**
 * Enrich a multiline word list with offline POS + meaning.
 *
 * Lines that already carry `| pos | meaning` are left unchanged. Missing
 * lookups stay as bare words. Sync and cheap — intended for "完成" / start.
 */
export function enrichWordListText(text: string): string {
  return parseWords(text)
    .map((line) => {
      const entry = parseWordLine(line);
      if (entry.pos || entry.meaning) return line;

      const speakable = speakTextFromEntry(line);
      const meta = lookupWordMeta(speakable);
      if (!meta || (!meta.pos && !meta.meaning)) return line;

      return entryToLine({
        word: entry.word,
        pos: meta.pos,
        meaning: meta.meaning,
      });
    })
    .join("\n");
}
